use winit::keyboard::{Key as WinitKey, NamedKey};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    Escape,
    Space,
    Enter,
    Backspace,
    Tab,
    LShift,
    RShift,
    LCtrl,
    RCtrl,
    LAlt,
    RAlt,
}

impl Key {
    pub fn from_winit(key: &WinitKey) -> Option<Key> {
        match key {
            WinitKey::Character(c) => match c.as_str() {
                "a" => Some(Key::A),
                "b" => Some(Key::B),
                "c" => Some(Key::C),
                "d" => Some(Key::D),
                "e" => Some(Key::E),
                "f" => Some(Key::F),
                "g" => Some(Key::G),
                "h" => Some(Key::H),
                "i" => Some(Key::I),
                "j" => Some(Key::J),
                "k" => Some(Key::K),
                "l" => Some(Key::L),
                "m" => Some(Key::M),
                "n" => Some(Key::N),
                "o" => Some(Key::O),
                "p" => Some(Key::P),
                "q" => Some(Key::Q),
                "r" => Some(Key::R),
                "s" => Some(Key::S),
                "t" => Some(Key::T),
                "u" => Some(Key::U),
                "v" => Some(Key::V),
                "w" => Some(Key::W),
                "x" => Some(Key::X),
                "y" => Some(Key::Y),
                "z" => Some(Key::Z),
                "0" => Some(Key::Num0),
                "1" => Some(Key::Num1),
                "2" => Some(Key::Num2),
                "3" => Some(Key::Num3),
                "4" => Some(Key::Num4),
                "5" => Some(Key::Num5),
                "6" => Some(Key::Num6),
                "7" => Some(Key::Num7),
                "8" => Some(Key::Num8),
                "9" => Some(Key::Num9),
                _ => None,
            },
            WinitKey::Named(named) => match named {
                NamedKey::ArrowLeft => Some(Key::ArrowLeft),
                NamedKey::ArrowRight => Some(Key::ArrowRight),
                NamedKey::ArrowUp => Some(Key::ArrowUp),
                NamedKey::ArrowDown => Some(Key::ArrowDown),
                NamedKey::Escape => Some(Key::Escape),
                NamedKey::Space => Some(Key::Space),
                NamedKey::Enter => Some(Key::Enter),
                NamedKey::Backspace => Some(Key::Backspace),
                NamedKey::Tab => Some(Key::Tab),
                NamedKey::Shift => Some(Key::LShift),
                NamedKey::Control => Some(Key::LCtrl),
                NamedKey::Alt => Some(Key::LAlt),
                _ => None,
            },
            _ => None,
        }
    }
}
